- name: Installing stow
  homebrew:
    name: stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:kjempehjerne/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./unix
  tags:
    - install
    - dotfiles
    - stow
